### ISSUE TITLE
Source JARs produced by assemble-maven have inconsistent package prefix

### ISSUE THREAD

**Issue by lolski** [vaticle/bazel-distribution#298]
## Description

Source JARs produced by assemble-maven have inconsistent package prefix. The inconsistency was observed between `protocol` and `grabl-tracing`.

Source JAR is produced with the prefix appended twice `grakn/protocol/grakn/protocol`.

## Environment

1. OS (where Grakn server runs): The issue was observed on a Mac

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Go to `protocol` and build a Maven artifact there:
1. `git checkout 71b277adb6b2ad249da4d1f5e2ae9079b0d70a48`
2. `bazel build //grpc/java:assemble-maven`
3. `vim bazel-bin/grpc/java/io.grakn.protocol:grakn-protocol-sources.jar`

Next, go to `grabl-tracing and build a Maven artifact there too:
1. `git checkout e0ca77dc22585a886e4d831c6d6384f162d891cd`
2. `bazel build //client:assemble-maven`
3. `vim bazel-bin/client/io.grabl:grabl-tracing-client-sources.jar`

## Expected Output

Source JAR is produced with the correct package prefix in both `protocol` and `grabl-tracing`:
- In the case of `protocol`, an entry in the source JAR should be prefixed with `grakn/protocol`, eg., `grakn/protocol/AnswerProto.java`.
- In the case of `grabl-tracing`, an entry in the source JAR should be prefixed with `grabl/tracing`, eg., `grabl/tracing/client/GrablTokenAuthClientInterceptor.java`

## Actual Output

Source JAR is produced with the correct package prefix  for `grabl-tracing`, but not `protocol`:
- In the case of `protocol`, an entry in the source JAR is prefixed with `grakn/protocol`twice, ie., `grakn/protocol/grakn/protocol/AnswerProto.java`.
- In the case of `grabl-tracing`, an entry in the source JAR is correctly prefixed with `grabl/tracing`, eg., `grabl/tracing/client/GrablTokenAuthClientInterceptor.java`

**Comment by vmax** [comment]
@lolski I believe this is not a bug in how we implemented the rule, but instead the bug in how we used it.

We're only supposed to add `source_jar_prefix` if it's the library we pack ourselves (such as Client Java) and if its source tree represents class structure _without_ a prefix; say, `grakn.client.core.CoreClient` is located in `core/CoreClient.java` and therefore for source JAR to be valid we have to prefix it with `grakn/client/`: `grakn/client/core/CoreClient.java`.

Both targets that you've added don't have source code written by us and instead have a generated code by gRPC - which already respects class-to-source mapping and therefore would produce a source jar corresponding to what class jar looks like. 

Therefore, to fix it, we shall remove `source_jar_prefix` attribute from those generated targets and only keep it for code we wrote 
ourselves.

**Comment by lolski** [comment]
I see. As a user I find it unclear on when to add `source_jar_prefix` and when not to. I can imagine other people would find it unclear too. How do we remedy it @vmax ?

**Comment by lolski** [comment]
I've found a case where a single JAR may be partially correct, that is it contain one file that has the correct path, and another that has an incorrect path. The target in question is `//protocol:assemble-maven`.

Set the `source_jar_prefix` of the target to empty (`""`) and then try to inspect the content of the source JAR:

```
$ bazel build //protocol:assemble-maven
vim bazel-bin/protocol/io.grabl:grabl-tracing-protocol-sources.jar
```

You'll see that:
- `grabl.tracing.protocol.util.ProtobufUUIDUtil` is incorrectly located in `protocol/util/ProtobufUUIDUtil.java`
- `grabl.tracing.protocol.TracingProto` is correctly located in `grabl/tracing/protocol/TracingProto.java`

**Comment by lolski** [comment]
The current way of adding the prefix isn't working well and we need to refine it.

This is how we should do it, unless you see a better way: given that the final file path of the source file needs to match the package, we should use the package address to determine where to place it in the JAR.
