### ISSUE TITLE
Support for bundling local JARs

### ISSUE THREAD

**Issue by sugarmanz** [vaticle/bazel-distribution#335]
In Gradle, for local vendor JARs, we would zip them in the JAR to publish, such that the published JAR had what it needed to compile and be included as a dependency for other modules:

```kotlin
tasks.named<Jar>("jar") {
    from(localLibs.map {
        if (it.isDirectory) it else zipTree(it)
    })
}
```

Trying to set that up with Bazel looks like this:

```bazel
java_import(
    name = "local_jar",
    jars = [
        ":local-jar.jar",
    ],
)

java_library(
    name = "my_lib",
    srcs = glob(["src/main/**/*"])
    exports = [
        ":local_jar",
    ],
)

assemble_maven(
    name = "my_lib_assemble",
    target = ":my_lib",
    version_file = "//:VERSION",
    workspace_refs = "@plugin_workspace_refs//:refs.json",
)

deploy_maven(
    name = "my_lib_deploy",
    target = "my_lib_assemble",
    release = "...",
    snapshot = "...",
)
```

I get an error about when the `deploy_maven` rule tries to aggregate dependency info:

```
ERROR: BUILD: in @vaticle_bazel_distribution//maven:rules.bzl%aggregate_dependency_info aspect on java_import rule //:local_jar: 
Traceback (most recent call last):
	File "/external/vaticle_bazel_distribution/maven/rules.bzl", line 199, column 78, in _aggregate_dependency_info_impl
		class_jar = target[OutputGroupInfo].compilation_outputs.to_list()[0],
Error: index out of range (index is 0, but sequence has 0 elements)
```

**Comment by alexjpwalker** [comment]
Hi there! The way we typically attach dependency JARs to be bundled into `assemble_maven` is by simply declaring them as `deps` of our `java_library` rules. We've actually never used a `java_library` with `exports` before. To help me understand: is it just for getting a direct translation of the Gradle build file, or is there another reason?

We have an example of bundling a `java_import` JAR into an `assemble_maven` assembly here: https://github.com/vaticle/dependencies/blob/master/library/rocksdbjni/BUILD#L40-L76
```py
genrule(
    name = "compile-mac",
    outs = [
        "rocksdbjni-osx.jar",
        "rocksdbjni-sources.jar",
    ],
    srcs = ["VERSION"],
    cmd = "$(execpath :builder-mac) && read -a outs <<< '$(OUTS)' && mv rocksdbjni-osx.jar $${outs[0]} && mv rocksdbjni-sources.jar $${outs[1]}",
    tools = ["@bazel_tools//tools/jdk:current_host_java_runtime", ":builder-mac"],
    tags = ["manual"]
)

java_import(
    name = "rocksdbjni-dev-mac",
    jars = ["rocksdbjni-osx.jar"],
    srcjar = "rocksdbjni-sources.jar",
    tags = ["manual", "no-ide", "maven_coordinates=org.rocksdb:rocksdbjni-dev-mac:{pom_version}"],
)

assemble_maven(
    name = "assemble-maven-mac",
    project_description = "RocksDB JNI Mac Dev release by Vaticle",
    project_name = "RocksDB JNI Mac Dev",
    project_url = "https://github.com/vaticle/dependencies",
    scm_url = "https://github.com/vaticle/dependencies",
    target = ":rocksdbjni-dev-mac",
    version_file = "VERSION",
    workspace_refs = "@vaticle_dependencies_workspace_refs//:refs.json",
)

deploy_maven(
    name = "deploy-maven-mac",
    target = ":assemble-maven-mac",
    snapshot = deployment["maven.snapshot"],
    release = deployment["maven.release"],
    tags = ["manual"]
)
```

**Comment by sugarmanz** [comment]
Hey @alexjpwalker, the example you have here is directly publishing a JAR that is compiled via a different step and imported w/ `java_import`. The JARs we have that are imported with `java_import` are 3rd party vendor JARs that we cannot publish by themselves, as we don't own that domain. 

Here is a minimal repo that reproduces the problem:
https://github.com/sugarmanz/bazel-distribution-local-jars

`main` is currently pointed to my branch of `bazel-distribution`, but checking out `problem-1` will show the original problem I'm attempting to solve here against `master` of `bazel-distribution`.

In my repo, you can see that I'm using the `java_import` as a dependency of, and exposed as part of (`api` dep in Gradle), the library I'm trying to publish, `lib-a`:
https://github.com/sugarmanz/bazel-distribution-local-jars/blob/main/lib-a/BUILD#L9
