### ISSUE TITLE
error using assemble-maven

### ISSUE THREAD

**Issue by nicholasphair** [vaticle/bazel-distribution#363]
Hi all,

I am unable to use the `assemble-maven` rule in my project. It fails with,
> ERROR: Cannot run target //:assemble-maven: Not executable

I can recreate this with other repositories too. For instance,
```
$ git clone https://github.com/vaticle/typedb-client-java.git
$ cd typedb-client-java
$ bazel run //:assemble-maven
....
ERROR: Cannot run target //:assemble-maven: Not executable
INFO: Elapsed time: 0.186s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Am I doing something wrong? I am able to run `deploy_maven` with more success.

Thanks.
Nick.

**Comment by jamesreprise** [comment]
Hi @nicholasphair,

`assemble_maven` isn't an executable rule, therefore `bazel run [...]` won't succeed here. `bazel build //:assemble-maven` in the context you gave will succeed, building:
```
Target //:assemble-maven up-to-date:
  bazel-bin/assemble-maven_pom.xml
  bazel-bin/com.vaticle.typedb:typedb-client.jar
  bazel-bin/com.vaticle.typedb:typedb-client-sources.jar
```

**Comment by nicholasphair** [comment]
Ah! Thank you very much for the quick reply. Sorry, I'm new to bazel!
