### ISSUE TITLE
version_file doesn't trim the version

### ISSUE THREAD

**Issue by anuragagarwal561994** [vaticle/bazel-distribution#380]
When using a `version_file` we don't trim the version mentioned inside the file.

Some of the IDEs are configured to put new line on file save by default, in those cases this becomes a problem as there will be a newline and the jars are tried to be published including new-line which fails.

**Comment by nhumblot** [comment]
Thank you for opening this. It caused https://github.com/jeremylong/DependencyCheck/pull/6705

**Comment by farost** [comment]
Our `assemble-maven` snapshot doesn't have trimming for versions, indeed, which is a problem.

We don't face this issue only because we use `--define version=$(cat VERSION)` in our test and release pipelines.

**Comment by nhumblot** [comment]
Thank you for your reactivity!
